language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra
script: ./build.sh
env:
  global:
  - NEXUS_USERNAME=mnuboci
  - SIGNING_SECRETKEYRINGFILE=../gradle/mnubo.secring.gpg
  - SIGNING_KEYID=043C6E1F
  # SIGNING_PASSWORD
  - secure: KkCkMQhf6BQ+c+sXKWnoBRaaJum9aHftK+Jqn9ok44iDojhBKpBn+ln7r3whj2swLtVkv4zwitDrVo/GOVFlBm80G/P79gefezRcx7WiXJy8hWWAtx5qpjvRxcBJX4Xxleen1QqGInEadjzxtaJQAIYnRAjjiUP6uGW+iPYX47C1XZ8zNfJ805XuSRJeRM1oWJOEOXHxgrQwCELizl3v32s3lNS5dyvHzERC3UfFk+aC2IC3bB+dYtTOOF9cA478NVC/xnI/ZmTiGN2Q6IDZKKiHl5gdqR5Uqx/AGwtkF/RxqttDlTI5aJEbqh+Ofm1mgeoWfchnPMg1GaM5GdteiCc8YhSUxFjqAJY9NnW7gTczq0sFqRZteopwBH9Yb3wE1ecg+IbkcM0OHaZWj+n+t0r3Cq1dF6ctC8nGdqDScK+AwnizLkORjbH0Ql7Kj8JjGcQubAXoy4viJV/uCUiWFikN/bXO0NCjvNLWzFBgHik14CK6PMG3EKMj68ukWxEYavQ7MwxTUs3tQeYiVRNwqKakoFOGJrCsyP43pBUqswcK0CkCFjta99XUuvfAPojsAqEG2FLeMYfrF/e13t+FWM6JkcECPDrEqxPhqz5PuSymJnwVMb6mhmmfMccW74zPI5THvvpfyBLjfHqp2kUuBRS5uBWfpsv/YZgjA0bt3nw=
  # NEXUS_PASSWORD
  - secure: EEaJBPRKVh91Mg7tV7EMcmiaPCYXZpgaDU2kbUMvnMEX34VNZAbWsa3jOSgd/S8Uqq2V2jf1w6piuKvqZ8oareCXq2vVf+ehS0CvCgW8BAHdKkIWdT8towDj4aOUXq8CE2gokez6f8HNgoxtutD407d94BJFVdXk9ASAifX4/fCjNDtQinGJvgR1ZOFktKiF4vmq4ILpdYnadACQMo6HoxZuYLObIOUTfCVTuJ1UwyL0CTMS6VR301sxV6Mz11XjtkEUbZPb+pUOe7dGFjCXQoHgcrXmt61cDqMK3nzibZuk1NnYvNDWGV8oBg1vLbppGiVZsSvDeBCid+qofPq6I3Xhx0ZQ+p2h4H0ixKp7CpXQ0Ny+hUwlqcUuyW40+Qe0fFdzAxxsmpJW/3q7mpGPDG9s/E2XKVAF1+tF0bgi3feS7KK9Yzrw1r1ycO61zNwv8uW7M4a56tReMNCdtsWZpY8eF4selGBIUPslWpiNKLa4TFmMNxKVVuPwL9C7WqPY3C21Lusk1w9jBPkGUdOHp5cAO5Oh8laM8220405ai1emVcTetqCv3vi1PqzHIup5EYVT1WVE+XAISbq/q51GpzIw33w1jx6iaUoB4pwmkSkZe1RKTws8lX/MahPRnXlmhnsDNLUVmB0MqbcvOQgdRqGwrbQBcQkxiw0+HxcuU6E=
