language: android
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra
script: ./build.sh
env:
  global:
  - NEXUS_USERNAME=mnuboci
  - SIGNING_SECRETKEYRINGFILE=../gradle/mnubo.secring.gpg
  - secure: jg8IdnBe6t8gXD+m6RTUnmrKkoq5D17ix8hm5IisE8cTPSH4ZTN9kcu/fZ4KW26HLvqXjGNmNJ4AP+TMkGjYIhNhs1wVnX7qkNbmwhgjYtpxN9cEuI58IJBUKsLDeNmXcRpMGwvta3C0N17iyJ97RhExj9xSP6a7P09DAANVowk=
  - secure: del1HTxbwZ6YJXBMyLHLEyPt3b3sikv1i1RI+wsFYn/JiCYOsxDXaI3WsatRPp4Zh/a7R9OFBOgNMo+igc0o6Yj0bEqwQJIyqKpA93O7v3x9xEUTqerEy/LuBdvzTrmQSoAnWP/GeavjBd4D+5BwwRXCJnB29Rkvlw1wkl5UCAc=
  - secure: F+Qctq95gES2a7PlCeANYaQwi5FH46Ee74ycSCFUnEgqYugl4IC8RY3U34xwM3OGhmF9XzYd8wuitGFkuZikcLnwigRA+7czM2/5xp3X0fzTp5Mtv4h3FEdn6xizMT+6KE/PmFoznS6C73iOqV2hb8iRRtG/zujWLxHToa/DOjs=